using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace TedToolkit.FileSystem.ProjectPaths;

/// <summary>
/// Generates strongly typed paths selected from the current Git work tree.
/// </summary>
[Generator]
public sealed class ProjectPathsGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor _missingGitRoot = new(
        "TTFS001",
        "Git work tree was not found",
        "TedToolkit.FileSystem.ProjectPaths requires the project to be inside a Git work tree.",
        "TedToolkit.FileSystem.ProjectPaths",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor _nameCollision = new(
        "TTFS002",
        "Generated member name collision",
        "The paths '{0}' and '{1}' both generate the member name '{2}'. Set Name metadata to resolve the collision.",
        "TedToolkit.FileSystem.ProjectPaths",
        DiagnosticSeverity.Error,
        true);

    /// <summary>
    /// Registers the incremental generator pipeline.
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var options = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) => GeneratorOptions.Create(provider.GlobalOptions));
        context.RegisterSourceOutput(options, static (productionContext, generatorOptions) => Generate(productionContext, generatorOptions));
    }

    private static void Generate(SourceProductionContext context, GeneratorOptions options)
    {
        if (string.IsNullOrWhiteSpace(options.GitDirectory) || !Directory.Exists(options.GitDirectory))
        {
            context.ReportDiagnostic(Diagnostic.Create(_missingGitRoot, Location.None));
            return;
        }

        var root = new DirectoryNode(string.Empty, options.GitDirectory, null);
        foreach (var path in options.Paths)
            AddMatches(root, path, options.GitDirectory, context);

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(options.RootNamespace))
        {
            source.Append("namespace ").Append(options.RootNamespace).AppendLine(";");
            source.AppendLine();
        }

        AppendRoot(source, root, options, context);
        context.AddSource("TedToolkit.FileSystem.ProjectPaths.g.cs", source.ToString());
    }

    private static void AddMatches(DirectoryNode root, PathPattern pattern, string gitDirectory, SourceProductionContext context)
    {
        var absolutePattern = Path.GetFullPath(Path.Combine(gitDirectory, pattern.Include));
        var hasWildcard = absolutePattern.IndexOfAny(new[] { '*', '?' }) >= 0;
        var candidates = hasWildcard
            ? Enumerate(gitDirectory, pattern.Kind).Where(path => IsMatch(absolutePattern, path))
            : new[] { absolutePattern };

        foreach (var candidate in candidates)
        {
            var isDirectory = Directory.Exists(candidate);
            var isFile = File.Exists(candidate);
            if ((pattern.Kind == PathKind.DIRECTORY && !isDirectory) || (pattern.Kind == PathKind.FILE && !isFile))
                continue;
            if (!isDirectory && !isFile)
                continue;

            var relativePath = GetRelativePath(gitDirectory, candidate);
            if (relativePath.StartsWith("..", System.StringComparison.Ordinal))
                continue;

            var segments = relativePath.Split(new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar }, System.StringSplitOptions.RemoveEmptyEntries);
            var directory = root;
            var lastDirectorySegment = isDirectory ? segments.Length : segments.Length - 1;
            for (var index = 0; index < lastDirectorySegment; index++)
                directory = directory.GetOrAddDirectory(segments[index], Path.Combine(directory.FullPath, segments[index]));

            if (isFile && segments.Length > 0)
                directory.AddFile(segments[segments.Length - 1], candidate, pattern.Name, context);
        }
    }

    private static IEnumerable<string> Enumerate(string root, PathKind kind)
    {
        if (kind == PathKind.DIRECTORY)
            return Directory.EnumerateDirectories(root, "*", SearchOption.AllDirectories);
        if (kind == PathKind.FILE)
            return Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories);
        return Directory.EnumerateFileSystemEntries(root, "*", SearchOption.AllDirectories);
    }

    private static string GetRelativePath(string root, string path)
    {
        var rootUri = new System.Uri(AppendDirectorySeparator(root));
        var pathUri = new System.Uri(path);
        return System.Uri.UnescapeDataString(rootUri.MakeRelativeUri(pathUri).ToString())
            .Replace('/', Path.DirectorySeparatorChar);
    }

    private static string AppendDirectorySeparator(string path)
    {
        return path.EndsWith(Path.DirectorySeparatorChar.ToString(), System.StringComparison.Ordinal)
            ? path
            : path + Path.DirectorySeparatorChar;
    }

    private static bool IsMatch(string pattern, string value)
    {
        var expression = Regex.Escape(pattern.Replace('\\', '/'))
            .Replace("\\*\\*/", "(?:.*/)?")
            .Replace("\\*", "[^/]*")
            .Replace("\\?", "[^/]");
        return Regex.IsMatch(value.Replace('\\', '/'), "^" + expression + "$", RegexOptions.CultureInvariant);
    }

    private static void AppendRoot(StringBuilder source, DirectoryNode root, GeneratorOptions options, SourceProductionContext context)
    {
        source.AppendLine("/// <summary>");
        source.AppendLine("/// Provides paths explicitly selected by TedToolkitFileSystemPath items.");
        source.AppendLine("/// </summary>");
        source.AppendLine("public static class ProjectPaths");
        source.AppendLine("{");
        AppendProperty(source, 1, "DirectoryPath", "Git", options.GitDirectory, "Represents the Git work tree root.");
        AppendProperty(source, 1, "FilePath", "Project", options.ProjectFile, "Represents the current project file.");
        AppendChildren(source, root, 1, context);
        source.AppendLine("}");
    }

    private static void AppendChildren(StringBuilder source, DirectoryNode directory, int indent, SourceProductionContext context)
    {
        foreach (var child in directory.Directories.Values.OrderBy(static item => item.Identifier, System.StringComparer.Ordinal))
        {
            AppendIndent(source, indent);
            source.AppendLine("/// <summary>");
            AppendIndent(source, indent);
            source.Append("/// Represents the directory <c>").Append(XmlEscape(child.FullPath)).AppendLine("</c>.");
            AppendIndent(source, indent);
            source.AppendLine("/// </summary>");
            AppendIndent(source, indent);
            source.Append("public static class ").Append(child.Identifier).AppendLine();
            AppendIndent(source, indent);
            source.AppendLine("{");
            AppendProperty(source, indent + 1, "DirectoryPath", "Directory", child.FullPath, "Represents this directory.");
            AppendChildren(source, child, indent + 1, context);
            source.AppendLine();
            AppendIndent(source, indent);
            source.AppendLine("}");
        }

        foreach (var file in directory.Files.Values.OrderBy(static item => item.Identifier, System.StringComparer.Ordinal))
            AppendProperty(source, indent, "FilePath", file.Identifier, file.FullPath, "Represents this file.");
    }

    private static void AppendProperty(StringBuilder source, int indent, string type, string identifier, string fullPath, string summary)
    {
        AppendIndent(source, indent);
        source.AppendLine("/// <summary>");
        AppendIndent(source, indent);
        source.Append("/// ").Append(summary).AppendLine();
        AppendIndent(source, indent);
        source.Append("/// Full path: <c>").Append(XmlEscape(fullPath)).AppendLine("</c>.");
        AppendIndent(source, indent);
        source.AppendLine("/// </summary>");
        AppendIndent(source, indent);
        source.Append("public static global::TedToolkit.FileSystem.").Append(type).Append(' ').Append(identifier)
            .Append(" { get; } = new(\"").Append(CSharpEscape(fullPath)).AppendLine("\");");
    }

    private static void AppendIndent(StringBuilder source, int indent) => source.Append(' ', indent * 4);

    private static string CSharpEscape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string XmlEscape(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private enum PathKind { FILE, DIRECTORY, ANY }

    private sealed class GeneratorOptions
    {
        public string RootNamespace { get; private set; } = string.Empty;
        public string ProjectFile { get; private set; } = string.Empty;
        public string GitDirectory { get; private set; } = string.Empty;
        public IReadOnlyList<PathPattern> Paths { get; private set; } = System.Array.Empty<PathPattern>();

        public static GeneratorOptions Create(AnalyzerConfigOptions options)
        {
            options.TryGetValue("build_property.RootNamespace", out var rootNamespace);
            options.TryGetValue("build_property.TedToolkitFileSystemProjectFile", out var projectFile);
            options.TryGetValue("build_property.TedToolkitFileSystemGitDirectory", out var gitDirectory);
            options.TryGetValue("build_property.TedToolkitFileSystemPaths", out var paths);
            return new GeneratorOptions
            {
                RootNamespace = rootNamespace ?? string.Empty,
                ProjectFile = projectFile ?? string.Empty,
                GitDirectory = gitDirectory ?? string.Empty,
                Paths = (paths ?? string.Empty).Split(new[] { '|' }, System.StringSplitOptions.RemoveEmptyEntries).Select(PathPattern.Create).ToArray(),
            };
        }
    }

    private sealed class PathPattern
    {
        public string Include { get; private set; } = string.Empty;
        public PathKind Kind { get; private set; } = PathKind.ANY;
        public string Name { get; private set; } = string.Empty;

        public static PathPattern Create(string value)
        {
            var values = value.Split(new[] { '~' }, 3);
            return new PathPattern
            {
                Include = values[0],
                Kind = values.Length > 1 && System.Enum.TryParse(values[1], true, out PathKind kind) ? kind : PathKind.ANY,
                Name = values.Length > 2 ? values[2] : string.Empty,
            };
        }
    }

    private sealed class DirectoryNode
    {
        public DirectoryNode(string name, string fullPath, DirectoryNode? parent)
        {
            Name = name;
            FullPath = fullPath;
            Parent = parent;
            Identifier = ToIdentifier(name);
        }

        public string Name { get; }
        public string FullPath { get; }
        public DirectoryNode? Parent { get; }
        public string Identifier { get; }
        public Dictionary<string, DirectoryNode> Directories { get; } = new(System.StringComparer.Ordinal);
        public Dictionary<string, FileNode> Files { get; } = new(System.StringComparer.Ordinal);

        public DirectoryNode GetOrAddDirectory(string name, string fullPath)
        {
            var identifier = ToIdentifier(name);
            if (!Directories.TryGetValue(identifier, out var directory))
            {
                directory = new DirectoryNode(name, fullPath, this);
                Directories.Add(identifier, directory);
            }
            return directory;
        }

        public void AddFile(string name, string fullPath, string configuredName, SourceProductionContext context)
        {
            var identifier = string.IsNullOrWhiteSpace(configuredName) ? ToIdentifier(name) : ToIdentifier(configuredName);
            if (Directories.TryGetValue(identifier, out var existingDirectory))
            {
                context.ReportDiagnostic(Diagnostic.Create(_nameCollision, Location.None, existingDirectory.FullPath, fullPath, identifier));
                return;
            }
            if (Files.TryGetValue(identifier, out var existingFile))
            {
                context.ReportDiagnostic(Diagnostic.Create(_nameCollision, Location.None, existingFile.FullPath, fullPath, identifier));
                return;
            }
            Files.Add(identifier, new FileNode(identifier, fullPath));
        }

        private static string ToIdentifier(string value)
        {
            var builder = new StringBuilder();
            var previousUnderscore = false;
            foreach (var character in value)
            {
                if (SyntaxFacts.IsIdentifierPartCharacter(character))
                {
                    builder.Append(character);
                    previousUnderscore = character == '_';
                }
                else if (!previousUnderscore)
                {
                    builder.Append('_');
                    previousUnderscore = true;
                }
            }

            var identifier = builder.ToString().Trim('_');
            if (identifier.Length == 0)
                identifier = "_";
            if (!SyntaxFacts.IsIdentifierStartCharacter(identifier[0]))
                identifier = "_" + identifier;
            if (SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None)
                identifier = "_" + identifier;
            return identifier;
        }
    }

    private sealed class FileNode
    {
        public FileNode(string identifier, string fullPath)
        {
            Identifier = identifier;
            FullPath = fullPath;
        }

        public string Identifier { get; }
        public string FullPath { get; }
    }
}
